#ifndef SPECTRA_VERSION_H
#define SPECTRA_VERSION_H

#define SPECTRA_FW_NAME "SPECTRA"
#define SPECTRA_FW_VERSION "0.1.0-bootstrap"

#ifndef SPECTRA_FW_BUILD_PROFILE_CSTR
#define SPECTRA_FW_BUILD_PROFILE_CSTR "debug"
#endif
#define SPECTRA_FW_BUILD_PROFILE SPECTRA_FW_BUILD_PROFILE_CSTR

#endif  // SPECTRA_VERSION_H
